export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const GET_DETAIL_EMPLOYEE = 'GET_DETAIL_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';