export const SEARCH_HISTORY = 'SEARCH_HISTORY';
export const GET_DETAIL_HISTORY = 'GET_DETAIL_HISTORY';
export const ADD_HISTORY = 'ADD_HISTORY';
export const EDIT_HISTORY = 'EDIT_HISTORY';
export const DELETE_HISTORY = 'DELETE_HISTORY';