export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const GET_DETAIL_LOCATION = 'GET_DETAIL_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';